### ISSUE TITLE
TODO: November-December

### ISSUE THREAD

**Issue by Destidom** [autograde/aguis#103]
Focus on these TODOs in November and December.

1. [x] Log rotate: Write a new log file each day instead of using screen as a file logger
     1. [x] Reduce SQL logging too?
2. [ ] Simpler Testing
3. [ ] Beautify the layout
    1. [ ] Group layout
    2. [ ] Members layout (Every other member should have a grey background)
4. [ ] Refresh page
    1. [ ] On Approve
    2. [x] On Group accept
5. [ ] Notification
6. [x] Rebuild button

**Comment by meling** [comment]
Closing this as it is out of date and imprecise.
